name: mobile_challenge_2021
description: Mobile Challenge 2021

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # For the transitions
  animations: ^2.0.0
  # For the list patients
  auto_size_text: ^2.1.0
  # To know if there is internet connection
  connectivity: ^3.0.3
  # For selecting the country
  country_picker: ^2.0.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # Get the current locale of the device
  devicelocale: ^0.4.1
  # For the blocks states
  equatable: ^2.0.0
  # For the static analysis tool
  extra_pedantic: ^1.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_localizations:
    sdk: flutter
  # For loading svg files
  flutter_svg: ^0.22.0
  # Locator service
  get_it: ^7.1.3
  # Http Requests
  http: ^0.13.3
  # For the i18n
  intl: ^0.15.3
  # For the i18n
  intl_translation: ^0.17.10+1
  # For the entities
  json_annotation: ^4.0.0
  # Language Picker
  language_pickers: ^0.2.0+1
  # For the logs
  logger: ^1.0.0
  # For the static analysis tool
  pedantic: ^1.11.0
  # For the utilities
  quiver: ^3.0.1
  # For the bloc
  rxdart: ^0.27.0
  # For the settings page
  settings_ui: ^1.0.0
  # Store settings
  shared_preferences: ^2.0.5
  # For better visualizing the stack traces
  stack_trace: ^1.10.0
  # For the models
  states_rebuilder: ^4.0.0+1
  # For the parser
  universal_html: ^2.0.1
  # For the static analysis tool
  very_good_analysis: ^2.0.0

  # flutter_launcher_icons: ^0.9.0
dependency_overrides:
  # For the intl_translation dependency error
  analyzer: ^1.4.0
  # For the intl_translation dependency error
  args: ^2.0.0
  # For the intl_translation dependency error
  build_config: ^1.0.0
  # For the intl_translation dependency error
  convert: ^3.0.0
  # For the intl_translation dependency error
  dart_style: ^2.0.0
  # For the i18n
  intl: ^0.17.0
  # For the dependency error
  petitparser: ^4.1.0
  # For the flutter_svg & flutter_launcher_icons dependency error
  xml: ^5.1.0

dev_dependencies:
  build_runner: ^2.0.3
  effective_dart: ^1.3.1
  flutter_driver:
     sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.1
  lint: ^1.5.3
  test: ^1.0.0

# From flutter_launcher_icons
flutter_icons:
  android: true
  adaptive_icon_background: "#003461"
  adaptive_icon_foreground: "assets/logo.png"
  ios: false
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/
    - assets/images/
    - assets/images/font_awesome/
    - assets/images/font_awesome/brands/
    - assets/images/font_awesome/solid/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
